### ISSUE TITLE
Unused `source-map` and `rewire` dependencies

### ISSUE THREAD

**Issue by MarcellPerger1** [insidewhy/process-pool#5]
`source-map` and `rewire` are listed as dependencies in `package.json` but I couldn't find anywhere where these are used. 
Can they be removed (or listed as devDependencies in `package.json`) or have I missed some usages?

**Comment by insidewhy** [comment]
Ah you're correct. I also should switch this project from `bluebird` to the native `Promise` implementation. When it was written, `bluebird` was much faster. Now it makes no sense.

**Comment by insidewhy** [comment]
I'm cleaning up the entire project to convert it to a more modern style, including adding typescript types and removing bluebird.
